from pydantic import BaseModel

class Data(BaseModel):
    MSSubClass : int 
    MSZoning : int
    LotArea : float
    Street : int
    Alley : int
    LotShape : int
    LandContour : int
    Utilities : int
    LotConfig : int
    LandSlope : int
    Neighborhood : int
    Condition1 : int
    Condition2 : int
    BldgType : int
    HouseStyle : int
    OverallQual : int
    OverallCond : int
    YearBuilt : int
    YearRemodAdd : int
    RoofStyle : int
    RoofMatl : int
    Exterior1st : int
    Exterior2nd : int
    MasVnrArea : float
    ExterQual : int
    ExterCond : int
    Foundation : int
    BsmtQual : int
    BsmtCond : int
    BsmtExposure : int
    BsmtFinType1 : int
    BsmtFinSF1 : float
    BsmtFinType2 : int
    BsmtFinSF2 : float
    BsmtUnfSF : float
    TotalBsmtSF : float
    Heating : int
    HeatingQC : int
    CentralAir : int
    Electrical : int
    firstFlrSF : float
    secondFlrSf : float
    LowQualFinSF : float
    GrLivArea : float
    BsmtFullBath : int
    BsmtHalfBath : int
    FullBath : int
    HalfBath : int
    BedroomAboveGrade : int
    KitchenAboveGrade : int
    KitchenQual : int
    TotRmsAbvGrd : int
    Functional : int
    Fireplaces : int
    FireplaceQu : int
    GarageType : int
    GarageYrBlt : int
    GarageFinish : int
    GarageCars : int
    GarageArea : float
    GarageQual : int
    GarageCond : int
    PavedDrive : int
    WoodDeckSF : float
    OpenPorchSF : float
    EnclosedPorch : float
    threeSsnPorch : float
    ScreenPorch : float
    PoolArea : float
    PoolQC : int
    Fence : int
    MiscFeature : int
    MiscVal : float
    MoSold : int
    YrSold : int
    SaleType: int
    SaleCondition : int